name: test

on:
  push:
    branches:
      - main

jobs:
  KSUForRaphael:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full ccache
          sudo apt clean
      - name: Cloning Kernel Tree
        run: |
          git clone https://github.com/SoDebug/kernel_raphael_sm8150.git --depth=1 -b ksu --recurse-submodules
      - name: Cloning Toolchain
        run: |
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1 --single-branch --no-tags -b master ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/SoDebug/AnyKernel3.git
      - name: Add KernelSU to Kernel Source Tree
        run: |
          cd kernel_raphael_sm8150
          curl -LSs "https://raw.githubusercontent.com/SoDebug/KernelSU/commit_ad4d8e939ebe6f55a1d50ace42a03e3fecd3c59a/kernel/setup.sh" | bash -
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/clang-r487747/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd kernel_raphael_sm8150
          make LLVM=1 LLVM_IAS=1 CC="ccache clang" CFLAGS="-Wno-error" raphael_defconfig
          make LLVM=1 LLVM_IAS=1 CC="ccache clang" CFLAGS="-Wno-error" -j$(grep -c ^processor /proc/cpuinfo)
          popd
      
      - name: Creating Config Info
        run: |
          echo "Device: RedMi K20 Pro 
          Source Code Tree: SOVIET-ANDROID branch:fixedmm
          Code: raphael
          Contain KernelSU: NO
          Build Code: $(date +%Y%m%d)_${GITHUB_SHA::8}
          For SOVIET-ANDROID Kernel 13.0(commit: ${GITHUB_SHA::8})
          " >> INFO.txt         
          
      - name: Packaging the Kernel
        run: |
          cp -v kernel_raphael_sm8150/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../Raphael-Kernel_SOVIET-ANDROID_commit_${GITHUB_SHA::8}.zip *
          popd
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Raphael-Kernel_SOVIET-ANDROID_commit_${GITHUB_SHA::8}.zip
          name: " Raphael-Kernel_SOVIET-ANDROID_commit_${GITHUB_SHA::8}"
          tag: " ${{ github.run_number }}_Raphael-Kernel_SA"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
