name: test

on:
  workflow_dispatch:

jobs:
  KSUForRaphael:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo apt update -y
          sudo apt-get install -y zip flex bison libncurses-dev gawk  libiberty-dev autoconf kmod bc build-essential gcc libc6 curl libstdc++6 git wget libssl-dev cpio p7zip-full ccache python2
          sudo apt clean
      - name: Cloning Sources and Toolchain
        run: |
          git clone https://github.com/LuanHalaiko/kernel_raphael_sm8150.git --depth=1 -b 3.0.5 --recurse-submodules
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 ~/clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/aarch64-linux-android-4.9
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-13.0.0_r0.13 --depth=1 --single-branch --no-tags ~/arm-linux-androideabi-4.9
          git clone https://github.com/SoDebug/AnyKernel3.git
#       - name: intergrate KernelSU
#         run: |
#           cd kernel_xiaomi_raphael
#           curl -LSs "https://raw.githubusercontent.com/SoDebug/KernelSU/main/kernel/setup.sh" | bash -
#           echo "CONFIG_DEBUG_SECTION_MISMATCH=y" >> arch/arm64/configs/raphael_defconfig
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          export PATH
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu
          export CROSS_COMPILE=aarch64-linux-android-
          export CROSS_COMPILE_ARM32=arm-linux-androideabi-
          output_dir=out
          pushd kernel_raphael_sm8150
          make LLVM=1 LLVM_IAS=1 CC="ccache clang" raphael_defconfig
          make LLVM=1 LLVM_IAS=1 CC="ccache clang" -j$(grep -c ^processor /proc/cpuinfo)
          popd
      - name: Creating Config Info
        run: |
          echo "Device: RedMi K20 Pro 
          Source Code Tree: Infinity branch:3.0.5
          Code: raphael
          Contain KernelSU: NO
          Build Code: $(date +%Y%m%d)_${{ github.run_number }}
          For Infinity Kernel 3.0.5
          " >> INFO.txt
          
      - name: Packaging the Kernel
        run: |
          cp -v kernel_raphael_sm8150/out/arch/arm64/boot/Image.gz \
                     AnyKernel3/
          pushd AnyKernel3
          7z a -mx9 ../Raphael-Kernel_Infinity_3.0.5.zip *
          popd
      - name: Uploading Kernel Package to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: Raphael-Kernel_Infinity_3.0.5.zip
          name: " Raphael-Kernel_Infinity_3.0.5"
          tag: " ${{ github.run_number }}_Raphael-Kernel_Infinity"
          bodyFile: "INFO.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
